package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
    try {
      com.example.countdown_flutter.CountdownFlutterPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.countdown_flutter.CountdownFlutterPlugin"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin countdown_flutter, com.example.countdown_flutter.CountdownFlutterPlugin", e);
    }
    try {
      snhyun.lee.flashy_tab_bar.FlashyTabBarPlugin.registerWith(shimPluginRegistry.registrarFor("snhyun.lee.flashy_tab_bar.FlashyTabBarPlugin"));
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin flashy_tab_bar, snhyun.lee.flashy_tab_bar.FlashyTabBarPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    } catch(Exception e) {
      Log.e(TAG, "Error registering plugin url_launcher_android, io.flutter.plugins.urllauncher.UrlLauncherPlugin", e);
    }
  }
}
